### ISSUE TITLE
can you please help me in fixing the following errors 

### ISSUE THREAD

**Issue by mriyazhussain** [anand498/Face-Liveness-Detection#14]
Requirement already satisfied: sklearn==0.0 in c:\users\m riyaz hussain\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from -r requirements.txt (line 4)) (0.0)
ERROR: Could not find a version that satisfies the requirement tensorflow==2.4.1 (from versions: 2.5.0rc0, 2.5.0rc1, 2.5.0rc2, 2.5.0rc3, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.6.0rc0, 2.6.0rc1, 2.6.0rc2, 2.6.0, 2.6.1, 2.6.2, 2.6.3, 2.7.0rc0, 2.7.0rc1, 2.7.0, 2.7.1, 2.8.0rc0, 2.8.0rc1, 2.8.0, 2.9.0rc0)
ERROR: No matching distribution found for tensorflow==2.4.1
PS D:\anand-Face-Liveness-Detection-master\anand-Face-Liveness-Detection-master>

**Comment by mriyazhussain** [comment]
PS D:\anand-Face-Liveness-Detection-master\anand-Face-Liveness-Detection-master> python main.py                                                           2022-04-14 15:05:40.458764: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2022-04-14 15:05:40.460287: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-04-14 15:05:49.619123: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found
2022-04-14 15:05:49.619371: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-04-14 15:05:49.629492: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: Madikera-Riyaz-Hussain
2022-04-14 15:05:49.629966: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: Madikera-Riyaz-Hussain
2022-04-14 15:05:49.632844: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "D:\anand-Face-Liveness-Detection-master\anand-Face-Liveness-Detection-master\main.py", line 4, in <module>
    predictperson()
  File "D:\anand-Face-Liveness-Detection-master\anand-Face-Liveness-Detection-master\livenessdetect\utils.py", line 15, in predictperson
    if cv2.waitKey(1) & 0xFF == ord('q'):
cv2.error: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:1334: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvWaitKey'
