### ISSUE TITLE
Can not build

### ISSUE THREAD

**Issue by csongorkeller** [anand498/Face-Liveness-Detection#9]
Hi there,
after running the script, this is the error I'm receiving:

```
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from livenessdetect.utils import predictperson
  File "/Users/csongorkeller/Desktop/Development/syntric/pretrained_models/Face-Liveness-Detection/livenessdetect/utils.py", line 1, in <module>
    from keras.preprocessing.image import img_to_array
  File "/Users/csongorkeller/opt/anaconda3/lib/python3.8/site-packages/keras/__init__.py", line 20, in <module>
    from . import initializers
  File "/Users/csongorkeller/opt/anaconda3/lib/python3.8/site-packages/keras/initializers/__init__.py", line 124, in <module>
    populate_deserializable_objects()
  File "/Users/csongorkeller/opt/anaconda3/lib/python3.8/site-packages/keras/initializers/__init__.py", line 49, in populate_deserializable_objects
    LOCAL.GENERATED_WITH_V2 = tf.__internal__.tf2.enabled()
AttributeError: module 'tensorflow.compat.v2.__internal__' has no attribute 'tf2'
```

**Comment by aditbaco** [comment]
sama here.

**Comment by anand498** [comment]
i hope you guys are using tensorflow==2.4.1. the latest version of tensorflow might not be compatible with the pre trained model.
